# Run linters and unit tests on the available Python 3 interpreter.  CI runs
# the latest Python via 'tox -e py3', so there's no version list to maintain.
[tox]
envlist = py3

# Run unit tests
# HACK: Pydocstyle fails to find tests.  Invoke a shell to use a glob.
[testenv]
setenv =
  PYTHONPATH = {toxinidir}
allowlist_externals = sh
extras = dev
commands =
  pycodestyle agiocli tests
  sh -c "pydocstyle agiocli tests/*"
  pylint agiocli tests
  check-manifest
  pytest -vvs --cov agiocli
